// Public copy only. Never fetch shop, order, account or storage data during this build.
const section = (heading, paragraphs, links = []) => ({ heading, paragraphs, links });
export const pages = {
  '/': {
    label: 'Home',
    title: 'PrintWithQR for Businesses | QR Print Orders & Queue',
    description: 'Give customers your business QR code for document uploads and manage print requests in one browser queue. Built for print counters, cyber cafés and hospital desks.',
    eyebrow: 'A SMARTER PRINT COUNTER FOR YOUR BUSINESS',
    h1: 'One QR code. Every print request in one queue.',
    intro: 'Put your business QR code at the counter. Customers scan it, upload files and choose print options. Your team reviews each request in one browser queue—without collecting files on WhatsApp.',
    sections: [
      section('Your counter, without the file-sharing clutter', ['Display your QR code where customers arrive. They open your upload page in a browser, choose a PDF or image and select the print options they need. Your team sees the request and its settings in the dashboard before printing.', 'Customers start from the QR code or link your business provides. Printing, payment and collection still happen at your counter.'], [['See the business workflow', '/how-it-works'], ['Explore QR printing', '/qr-printing'], ['See PrintWithQR features', '/features']]),
      section('One queue for every print request', ['Review incoming files in a browser dashboard, keep track of each job and update its status as your team prints. Set your own black-and-white and colour rates.', 'Customers pay your business directly for printing. Your PrintWithQR subscription covers the ordering platform; it does not include paper, ink or printing charges.'], [['Explore the print-counter workflow', '/for-print-shops'], ['Compare business plans', '/pricing'], ['Follow the setup guide', '/setup-guide']]),
      section('QR document ordering for staffed business counters', ['Print shops and cyber cafés can collect walk-in print requests without mixing documents into personal messaging accounts. Offices, schools, hotels, clinics and hospital print desks can use the same workflow where staff receive and print files at a counter. Register your business, set your rates and test the workflow with a non-sensitive sample file.'], [['Register your business', '/register'], ['Read common questions', '/faq'], ['Contact PrintWithQR', '/contact']]),
    ],
  },
  '/features': {
    label: 'Features', title: 'PrintWithQR Features – QR Printing & Online Print Orders',
    description: 'Explore business QR uploads, PDF and image support, print options, your own rates and a live order queue for staffed print counters.',
    h1: 'Printing features built for your counter', intro: 'Give customers a simple upload page and give your team a clear view of every incoming print request.',
    sections: [
      section('Your QR code opens a mobile upload page', ['Display your business QR code at the counter. Customers scan it to open your upload page and send PDFs or images without installing an app or using a messaging conversation. Ask customers to check your business name before uploading.']),
      section('Preview documents and choose print options', ['Preview supported documents and choose page ranges, black-and-white or colour, paper size and single- or double-sided options. Available choices and charges depend on the shop. Confirm any special instructions with the counter before printing.']),
      section('Private documents and authorized shop access', ['Customers upload against an authorization for one exact document location. Signed-in staff access only their shop’s orders and receive short-lived links for authorized documents. Changing a shop ID in a browser does not authorize another shop’s files.', 'Mark a job Completed or Cancelled when it is finished. Its working file becomes eligible for removal after 10 minutes. Downloaded copies on your counter computer need to be handled separately.'], [['Read document-handling answers', '/faq']]),
      section('A live queue for your team', ['The dashboard displays incoming orders and print settings. Your team can review files, open them for printing and move orders through pending, printing and completed states. Keep the dashboard open while accepting orders.']),
      section('Your business, your print rates', ['Configure your business name, address, printer details and black-and-white and colour rates. Customers pay your business directly. Platform subscriptions are separate from customer printing charges.'], [['Compare subscription pricing', '/pricing'], ['Explore the business workflow', '/for-print-shops'], ['See how the QR flow works', '/how-it-works']]),
    ],
  },
  '/how-it-works': {
    label: 'How It Works', title: 'How PrintWithQR Works for Businesses – QR to Print Queue',
    description: 'Display your business QR code, receive customer files and print settings, then manage each request in a browser queue.',
    h1: 'From your business QR to your print queue', intro: 'Customers use the QR code you display. Your team receives the request and stays in control of printing and collection.',
    sections: [
      section('1. Display your business QR code', ['Register your business and display its QR poster at a staffed counter. The code opens your upload page in the customer’s browser. Test it on a phone before putting it in front of customers.']),
      section('2. Let customers prepare the request', ['Customers choose PDFs or images, preview supported files, select available print options and review the estimated charge. For unusual paper, binding or a specific finish, they should ask your team about availability.']),
      section('3. Review every request in your queue', ['Your dashboard shows incoming files and print settings. Your team reviews each job before starting the printer. The QR code does not trigger unattended printing.']),
      section('4. Print, collect payment and hand over', ['Update the order status as you print. Customers pay your business directly and collect at your counter. PrintWithQR’s subscription checkout is for the business account, separate from customer printing charges.'], [['Explore print options', '/features'], ['See online printing for businesses', '/online-printing'], ['Read common questions', '/faq']]),
    ],
  },
  '/pricing': {
    label: 'Pricing', title: 'PrintWithQR Business Pricing – QR Print Orders',
    description: 'Try PrintWithQR with a 10-page business trial, then choose ₹99 for 30 days or ₹599 for 365 days. Customer printing charges go directly to your business.',
    h1: 'Simple pricing for your print counter', intro: 'Start with a 10-page trial. Choose a business subscription when you are ready to continue accepting orders.',
    pricing: true,
    sections: [
      section('What the subscription covers', ['The business subscription provides access to PrintWithQR’s QR upload and order-management platform. It does not include a printer, paper, ink, a physical QR stand or the cost of printing customer documents.', 'The trial is an allowance of 10 printed pages, not 10 orders. Page selections affect usage. Review the available allowance in your dashboard.']),
      section('Customers pay your business for printing', ['Your business sets its own printing rates and collects customer payments directly. PrintWithQR does not take a commission from those printing payments.']),
      section('Choose a plan when you need it', ['The monthly plan provides 30 days of access and the yearly plan provides 365 days. Review the plan and amount in the business checkout before paying through Razorpay.'], [['Register your business', '/register'], ['See the setup guide', '/setup-guide'], ['Contact PrintWithQR', '/contact']]),
    ],
  },
  '/for-print-shops': {
    label: 'For Businesses', title: 'QR Print Shop Software for Staffed Counters | PrintWithQR',
    description: 'Give your business a QR upload page, set your print rates and manage incoming orders in a browser dashboard. For print shops, cyber cafés and staffed print desks.',
    h1: 'A QR print-ordering system for your business', intro: 'Give customers one place to upload documents and keep incoming jobs organised at your counter—whether you run a print shop, cyber café or hospital print desk.',
    sections: [
      section('Turn your counter QR into an upload point', ['After registration, your dashboard provides your business QR code. Display it where customers can scan it. They open the upload page, choose files and settings, and send the order to your queue.']),
      section('A document-upload queue, not a full billing system', ['PrintWithQR handles QR document submission, print settings, per-page charges and the order queue. It does not replace stock management, a POS system or a medical-record system. Choose it when your main problem is receiving and organizing ready-to-print files at a staffed counter.'], [['See the available print features', '/features']]),
      section('Keep control of the printing', ['Open your dashboard on the computer you use at the counter. Review orders and print options before starting each job. Your printer remains under your control; check its connection, paper and print-dialog settings.', 'The platform sends documents and order details to your browser workflow. It does not promise unattended printing on every printer model.']),
      section('Set rates that match your business', ['Enter your business details and printing rates in the profile. Keep these current and confirm special jobs directly with customers. Customers pay your business, while you pay PrintWithQR separately for the platform subscription.']),
      section('Get ready to accept your first order', ['Start with the 10-page trial, scan your own QR code and submit a non-sensitive sample document. Confirm that the job reaches your queue and that the printout matches the settings.'], [['Follow the PrintWithQR setup guide', '/setup-guide'], ['Register your business', '/register'], ['View subscription pricing', '/pricing'], ['Get setup help', '/contact']]),
    ],
  },
  '/online-printing': {
    label: 'Online Printing', title: 'Online Printing Orders for Businesses | PrintWithQR',
    description: 'Offer QR-based PDF and image uploads at your print counter. Your business receives customer print requests in one browser queue.',
    h1: 'Offer online print orders at your counter', intro: 'Give customers your QR link so they can send ready-to-print PDFs or images while your team manages each request.',
    sections: [
      section('Accept files without a messaging thread', ['Customers open your business QR link in a browser and upload PDFs or images. A PDF helps preserve page layout; customers should check that image text is legible before submitting. PrintWithQR supports digital files, not paper originals.']),
      section('Receive print choices with the request', ['The upload flow lets customers select available page ranges, colour, paper and duplex options and review an estimated charge. Your team can confirm special instructions at the counter before printing.']),
      section('Keep the printing decision with your team', ['Each request reaches your business queue. Review the files and settings, then start printing when your counter is ready. Uploading does not guarantee an immediate or unattended printout.', 'Your business handles the physical printout, customer payment and collection. PrintWithQR provides the ordering platform, not nationwide delivery.']),
      section('Handle documents with care', ['Ask customers to keep their original files and submit only documents they are authorised to print. Protect downloaded working copies on shared counter computers and avoid treating the upload service as long-term storage.'], [['See the full business workflow', '/how-it-works'], ['Explore platform features', '/features'], ['Read common questions', '/faq']]),
    ],
  },
  '/online-xerox': {
    label: 'Online Xerox', title: 'Online Xerox Ordering for Shops & Cyber Cafés | PrintWithQR',
    description: 'Offer QR-based digital-file orders at your xerox counter or cyber café. Customers upload a PDF or scan; your team reviews each job.',
    h1: 'Bring QR ordering to your xerox counter', intro: 'Give customers a simple way to send digital files to your business, without collecting every PDF or image through WhatsApp.',
    sections: [
      section('Digital printing is different from copying paper', ['PrintWithQR sends digital files to your counter queue. If a customer has only a paper original, your team can photocopy it directly or ask for a clear scan. Uploading a photograph of a page is different from copying the physical original.']),
      section('Help customers send readable scans', ['A clear scan should show all page edges and sharp text. Customers can export several pages as a PDF before opening your QR upload page. Your team should check the file before printing.']),
      section('Confirm the print details at your counter', ['Customers choose available paper size, colour and copies after scanning your QR code. Confirm special forms, exact scale and finishing needs with them before starting the job. Your business sets the charge and collects payment directly.']),
      section('Start with your business QR', ['Register your counter, test its QR code with a non-sensitive PDF and confirm that the sample reaches your queue.'], [['Explore online print orders', '/online-printing'], ['How the QR workflow works', '/qr-printing'], ['See the business setup guide', '/for-print-shops']]),
    ],
  },
  '/qr-printing': {
    label: 'QR Printing', title: 'QR Printing for Businesses – Scan & Upload | PrintWithQR',
    description: 'See how your business QR code opens a browser upload page and sends customer documents to your print queue.',
    h1: 'One QR code for your business upload page', intro: 'Display your code at the counter so customers can send print requests straight to your business queue.',
    sections: [
      section('What the QR code does', ['The code opens your business upload link in a browser. It does not connect a phone directly to a printer or bypass your team’s review. Customers upload files and your team handles printing through the dashboard.']),
      section('For customers: check the destination', ['Use your phone camera to scan the code. Check the PrintWithQR domain and the shop name before selecting a document. Ask the counter for help if the code opens the wrong shop, a damaged link or an unfamiliar destination.']),
      section('Display a readable code at your counter', ['Download your QR poster from the dashboard and place it near the counter. Keep it flat, clear and large enough to scan. Test the printed code on a phone before customers use it, and replace damaged copies.']),
      section('Keep ordering separate from payment', ['The PrintWithQR upload code sends a printing order. Customers pay the shop directly using the methods the shop accepts. Do not label the upload QR as a payment QR.'], [['Set up your shop QR code', '/setup-guide'], ['See the complete ordering process', '/how-it-works'], ['Explore shop subscriptions', '/pricing']]),
    ],
  },
  '/faq': {
    label: 'FAQ', title: 'PrintWithQR Business FAQ – QR Print Orders',
    description: 'Answers for business owners about QR uploads, supported files, customer payments, subscriptions and print queue management.',
    h1: 'Business questions, answered', intro: 'Practical answers for owners and staff setting up a QR print-ordering counter.',
    sections: [
      section('Do customers need to install an app?', ['No. Customers open the shop’s QR link in their mobile browser and upload their files there.'], [['See how it works', '/how-it-works']]),
      section('Which files can I send?', ['The upload flow supports PDFs and images. Export editable documents to PDF first and check the preview before submitting.'], [['Prepare your document for printing', '/online-printing']]),
      section('Where do I pay for my printout?', ['Pay the participating print shop directly. Its printing charges are separate from the PrintWithQR subscription paid by shop owners.'], [['Understand pricing', '/pricing']]),
      section('Can I use any shop or order home delivery?', ['You need a QR code or upload link from a shop using PrintWithQR. Collection is arranged with that shop. PrintWithQR does not provide a nationwide home-delivery service.']),
      section('Does scanning the QR code print automatically?', ['No. The QR code opens the upload page. The shop reviews the order and controls printing from its dashboard.'], [['Learn about QR printing', '/qr-printing']]),
      section('What does the free trial include?', ['The shop trial allows 10 printed pages. It is a page allowance rather than 10 separate orders. Shop subscriptions cost ₹99 for 30 days or ₹599 for 365 days.'], [['Compare the plans', '/pricing']]),
      section('Can I keep my documents here as a backup?', ['No. Keep your original files. Uploaded files are private working copies. Completed or cancelled documents become eligible for deletion after 10 minutes, with a scheduled worker retrying removal. Pending and printing documents remain available to authorized shop staff. Shop downloads and printed copies are handled by the shop.']),
      section('How do I change or cancel a printing order?', ['Contact the shop promptly before it starts printing. The shop controls fulfilment, printing charges and remedies for the physical print job. For a platform subscription issue, contact PrintWithQR.'], [['Contact PrintWithQR', '/contact']]),
    ],
  },
  '/setup-guide': {
    label: 'Setup Guide', title: 'PrintWithQR Setup Guide – QR Printing for Your Business',
    description: 'Register your business, check print rates, open the dashboard and test your QR upload workflow before accepting customer documents.',
    h1: 'Set up PrintWithQR at your counter', intro: 'Prepare your business dashboard and test the complete workflow with a non-sensitive sample file.',
    sections: [
      section('1. Register your business', ['Have your business name, phone number, address and printer details ready. Choose a password and enter your black-and-white and colour rates. Keep your account credentials private.'], [['Open business registration', '/register']]),
      section('2. Review your profile and trial allowance', ['Sign in on the computer used at the counter. Check the shop details and rates in your profile. The initial allowance is 10 printed pages; choose a paid plan when you need to continue beyond it.'], [['Review subscription plans', '/pricing']]),
      section('3. Download and test your QR poster', ['Open the QR poster in your dashboard, download it and print a clear copy. Scan it with a phone, check the shop name and send a sample PDF with no personal information. Confirm it appears in the queue.']),
      section('4. Print a sample job', ['Review the copies, colour, paper and duplex settings. Open the document and check the printer dialog before printing. Confirm the physical result and update the order status. Browser and printer settings may require manual adjustment.']),
      section('5. Prepare your counter routine', ['Keep the dashboard open while accepting jobs. Explain where customers should pay and collect their documents. Sign out on shared computers, protect downloaded files and remove working copies when no longer needed.'], [['See the shop-owner workflow', '/for-print-shops'], ['Get setup help', '/contact']]),
    ],
  },
  '/register': {
    label: 'Register', title: 'Register Your Business – Start With PrintWithQR',
    description: 'Register your print counter with PrintWithQR. Start with a 10-page trial and create a QR upload workflow for your customers.',
    h1: 'Bring QR ordering to your business', intro: 'Create your business account, check your printing rates and try the workflow with a 10-page trial.',
    sections: [
      section('Have your business details ready', ['The registration form asks for your business name, phone number, password, address, printer information and printing rates. Use details you control and a password you do not share with customers.']),
      section('Understand the trial and plans', ['The trial provides a 10-page allowance for your business. After the trial, subscriptions are ₹99 for 30 days or ₹599 for 365 days. Your customers’ printing payments remain separate and go directly to your business.'], [['See plan details', '/pricing']]),
      section('Create your account', ['Continue to the registration form to enter your details. After registration, sign in to review your profile, get your QR poster and send a test order.'], [['Start business registration', '/register/start'], ['Already registered? Sign in', '/login'], ['Read the setup guide', '/setup-guide']]),
    ],
  },
  '/contact': {
    label: 'Contact', title: 'Contact PrintWithQR – Online Printing Platform',
    description: 'Contact PrintWithQR at shxbuild@gmail.com or +91 94830 30043 for platform and shop setup help. Find our official Instagram and YouTube profiles.',
    h1: 'Contact PrintWithQR', intro: 'For platform questions and shop setup, email shxbuild@gmail.com or call +91 94830 30043.',
    sections: [
      section('Email and phone support', ['Email shxbuild@gmail.com or call +91 94830 30043. Describe the issue and the step where you need help. Never send passwords, one-time codes or complete card details.'], [['Email PrintWithQR', 'mailto:shxbuild@gmail.com'], ['Call PrintWithQR', 'tel:+919483030043']]),
      section('Platform and shop setup questions', ['Tell us which setup step you need help with. Do not post passwords, full payment details, uploaded documents or customer information in social comments.'], [['Message PrintWithQR on Instagram', 'https://www.instagram.com/printwithqr/'], ['Visit PrintWithQR on YouTube', 'https://www.youtube.com/@printwithqr'], ['Read the setup guide', '/setup-guide']]),
      section('Questions about a printout or customer order', ['Contact the shop whose QR code you scanned. That shop handles the printing, collection, printing payment and any issue with the finished copies.']),
      section('Before you get in touch', ['The FAQ explains uploads, subscriptions and the difference between shop subscription payments and customer printing charges.'], [['Read PrintWithQR answers', '/faq'], ['Review subscription pricing', '/pricing']]),
    ],
  },
  '/privacy-policy': {
    label: 'Privacy Policy', title: 'Privacy Policy | PrintWithQR',
    description: 'PrintWithQR privacy policy covering shop accounts, uploaded documents, order information, retention and service providers.',
    h1: 'Privacy policy', intro: 'Effective date: 2 October 2026. This policy explains how PrintWithQR handles information used for business accounts and customer printing orders.',
    sections: [
      section('About PrintWithQR', ['PrintWithQR is the platform brand. Contact support at shxbuild@gmail.com or +91 94830 30043 for questions about the service or this policy.']),
      section('Information used to provide the service', ['Shop registration uses the shop name, phone number, address, printer details, printing rates and account credentials. The service also handles subscription status and payment references. Registration checks may use device identifiers, browser signals and network information to limit abuse.', 'Customer printing orders include uploaded documents, filenames, selected print options, the destination shop and order status. Upload only material you are authorised to share with the shop.']),
      section('How the information is used and shared', ['The service uses this information to operate accounts, route printing orders, support subscriptions, troubleshoot problems and limit misuse. The chosen print shop receives the documents and order details it needs to fulfil the job.', 'Vercel hosts the application, Supabase provides database, authentication and storage services, and Razorpay handles shop subscription checkout. The privacy terms of those providers also apply to their processing. Instagram and YouTube apply their own policies when you visit those services.']),
      section('Storage and retention', ['Uploaded files are working copies for printing, not permanent storage. Completed or cancelled documents become eligible for deletion after 10 minutes. A scheduled worker runs each minute and retries failed Storage API removals; pending and printing documents are preserved. Failures, retries, backups and files downloaded by shops can affect retention.', 'Order history is retained separately from uploaded documents. The dashboard may also keep order history in the shop browser. Shops should protect downloaded documents and remove them when no longer needed. The document-deletion period does not apply to account records, order history, anti-abuse records, payment references or provider backups. Contact support with questions about those records.']),
      section('Browser storage and security', ['The application uses browser storage for sign-in state, preferences and shop workflow information. Sign out on shared devices. Do not share account credentials or private order links.', 'Uploaded documents are stored in a private bucket. Shop document access requires authorization and uses short-lived signed links. Access controls and search-indexing exclusions are separate protections; a noindex instruction is not a guarantee of confidentiality.']),
      section('Privacy requests and changes', ['Send privacy questions or requests concerning access, correction or deletion to shxbuild@gmail.com or call +91 94830 30043. Describe the request without sending passwords or customer documents. Support may need to verify your authority before handling account or order information.', 'Changes to this policy will be published here with an updated effective date.']),
    ],
  },
  '/terms': {
    label: 'Terms', title: 'Terms of Service | PrintWithQR',
    description: 'PrintWithQR terms for shop accounts, document uploads, subscription access and the responsibilities of participating shops.',
    h1: 'Terms of service', intro: 'Effective date: 2 October 2026. These terms describe use of PrintWithQR for business printing workflows and customer document submission.',
    sections: [
      section('The service', ['PrintWithQR provides a browser-based platform for sending documents to participating print shops and managing their queues. The participating shop performs the physical printing and arranges customer payment and collection. PrintWithQR does not promise delivery or availability at every shop.']),
      section('Accounts and acceptable use', ['Provide accurate shop details, keep account credentials private and use the platform only for lawful printing orders. Upload only documents you own or are authorised to provide for printing. Do not attempt to access another person’s account, documents or orders, bypass access controls, or disrupt the service.']),
      section('Orders and printing responsibility', ['Customers should check the destination shop, file preview and settings before submitting. Shops should review instructions, final charges and printer settings before starting work. Direct questions about physical print quality, collection and printing payments to the shop.']),
      section('Shop subscriptions', ['The initial trial allows 10 printed pages. The confirmed subscription options are ₹99 for 30 days and ₹599 for 365 days. Printing consumables and customer printing charges are separate. Review the amount and selected plan at checkout.', 'Subscriptions provide platform access for the selected period. Contact support with questions about taxes, renewal, cancellation or service interruptions before purchasing. Subscription payment issues are covered by the refund policy.'], [['View the pricing page', '/pricing'], ['Read the refund policy', '/refund-policy']]),
      section('Availability and document handling', ['Keep original documents and do not rely on the platform as an archive. Browser, network, printer and service interruptions can affect an order. Shops are responsible for appropriate handling of documents they download and copies they produce.']),
      section('Issues and applicable rights', ['Contact shxbuild@gmail.com or +91 94830 30043 for support or to raise a complaint about the platform. These terms do not exclude rights that cannot lawfully be excluded.']),
    ],
  },
  '/refund-policy': {
    label: 'Refund Policy', title: 'Refund Policy | PrintWithQR',
    description: 'PrintWithQR subscription refund policy, payment-error support and the difference between platform subscriptions and shop printing charges.',
    h1: 'Refund policy', intro: 'Effective date: 2 October 2026. PrintWithQR does not offer voluntary refunds for shop subscriptions. This policy does not limit remedies required by applicable law.',
    sections: [
      section('Two different types of payment', ['Customers pay participating shops directly for printing. The shop handles questions about those charges, cancellations, reprints and physical print quality. PrintWithQR subscription payments purchase platform access for a shop account.']),
      section('No voluntary subscription refunds', ['Subscription payments are non-refundable for change of mind, unused access or a decision to stop using the platform. There is no voluntary refund window. Use the 10-page trial to evaluate the workflow and review the plan before paying. This policy does not exclude a refund or other remedy required by applicable law.']),
      section('Payment errors and access problems', ['For a duplicate charge, a successful payment that did not activate access or another payment error, email shxbuild@gmail.com or call +91 94830 30043. Provide the payment reference, date, plan and a description of the problem so the transaction and access can be checked.', 'Do not send card numbers, CVV, passwords or one-time codes. Payment errors and any remedies required by law will be handled according to the verified transaction and applicable requirements.']),
      section('Refund method', ['If a refund is legally required or a payment correction involves returning funds, the original payment route will be used when supported by the payment provider. Bank and provider processing times can vary. No fixed processing time is promised.'], [['Review the pricing', '/pricing'], ['Contact PrintWithQR', '/contact']]),
    ],
  },
};
